### ISSUE TITLE
Support for PCRE2

### ISSUE THREAD

**Issue by elfring** [mmottl/pcre-ocaml#10]
How are the chances to support [the current version (≧ “10.22”) of this programming interface for Perl-compatible regular expressions](http://www.pcre.org/ "Start page for PCRE")?

**Comment by mmottl** [comment]
The current PCRE-bindings satisfy my needs.  If you need further functionality, feel free to submit pull requests, but please make sure that the API stays backward compatible and that the library can be compiled with older PCRE versions.

**Comment by elfring** [comment]
Do you get any special software development concerns from introducing the usage of the prefix “pcre2” into the current source files?

**Comment by mmottl** [comment]
Yes, not everybody may have pcre2, there may be portability issues, etc.  It's probably going to take a significant effort to support the new API.  Not sure it's worth the effort.

**Comment by elfring** [comment]
* Do this kind of feedback mean that you would prefer to maintain several versions of your software library in parallel on topic branches?
* Which [branch organisation](https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows "Selection of development branches") will be selected?

**Comment by mmottl** [comment]
No, by this I meant that people use pcre on a large variety of platforms, some of which may not even have pcre2.  If you want to make sure that they can still use the older pcre installation, you would have to add potentially non-trivial autoconfiguration code.  You might also consider writing completely separate OCaml bindings for Pcre2 and leverage already existing OCaml code from the current bindings for that purpose.  It might make some problems (e.g. backward compatibility) easier to solve.

**Comment by elfring** [comment]
* How many software maintenance will be needed in parallel for the discussed versions?
* Would you like to choose any further topic and development branches?

**Comment by mmottl** [comment]
It would probably be best to just start a fresh tree and copy as much as possible from the previous version.  The amount of maintenance required will typically depend on the quality of the bindings (bugs) and how likely there will be portability issues.

**Comment by elfring** [comment]
I suggest to switch to the PCRE2 programming interface at a specific version of your OCaml library.
Which version number will be appropriate then?

**Comment by mmottl** [comment]
The latest release or even head of the master branch.  This should make it easiest to adopt future changes.

**Comment by elfring** [comment]
Will other branch names be a bit safer for corresponding patch merges?

**Comment by mmottl** [comment]
There are currently no other branches.  Feature branches are typically merged and eventually deleted.

**Comment by elfring** [comment]
I suggest to introduce a clearer separation between development branches.

**Comment by elfring** [comment]
How do you think about to use any software improvements which are mentioned in [the PCRE change log](https://vcs.pcre.org/pcre2/code/trunk/ChangeLog?revision=666&view=markup "Software evolution for PCRE2")?

**Comment by mmottl** [comment]
If I had a personal need for a feature, I would implement it, but the current PCRE API satisfies my needs.  Feel free to contribute any patches that support unimplemented features.

**Comment by elfring** [comment]
Do your needs (or requirements by other contributors) evolve in a way which can include the use of a software like “PCRE 10.32”?

**Comment by mmottl** [comment]
My needs in that respect haven't changed.

**Comment by elfring** [comment]
Thanks for another feedback.

* I am curious under which circumstances more users would prefer to stop working with outdated software.
* I would generally prefer to work with more recent software components for some uses cases. Would you ever like to help here another bit?

**Comment by elfring** [comment]
[The PCRE software was improved several times in the meantime](https://vcs.pcre.org/pcre2/code/trunk/ChangeLog?revision=1044&view=markup "PCRE change log").

* It seems that OCaml programmers get more unwanted technical difficulties then.
* Is it really hard to find companions with similar software development interests?

**Comment by mmottl** [comment]
I'm not aware of any technical issues with the current PCRE library.  It has all the features I need and works flawlessly and efficiently.

Yes, as a matter of fact it is difficult to find people with similar software development interests.  I have certainly never succeeded in getting my problems fixed by just waiting for other people to do that.

**Comment by elfring** [comment]
* I hoped that you know more nice OCaml programmers (than me).
* You might have lost interest in more significant extensions for this software library. I am curious if more incentives can be offered besides mentioned update possibilities which would be meaningful and useful also for you.

**Comment by elfring** [comment]
I am just looking again for possibilities and system preparations for corresponding software adjustments.
