### ISSUE TITLE
Selection of additional build variants for the PCRE library

### ISSUE THREAD

**Issue by elfring** [mmottl/pcre-ocaml#11]
Information on the PCRE configuration (build-time options) is provided. A few software build parameters like [“code unit size” and “internal linkage setting”](http://www.pcre.org/current/doc/html/pcre2limits.html "Limitations of the PCRE library") have got an important influence on the kind (and length) of regular expressions that can be processed.

I assume that all of them should be directly supported by the library “PCRE-OCaml” somehow.

* I suggest to make these variants selectable by the mentioned build parameters.
* Can additional variants be built on demand if a specific configuration was not installed by default in a run time environment?

**Comment by mmottl** [comment]
These are PCRE2 options.  If you implement an API for PCRE2, you may consider adding them.  It is probably a good idea to keep PCRE1- and PCRE2-specific options as well as functions separate though, because developers need to know whether or not their code will eventually depend on PCRE2.  If you implement completely separate bindings, that problem doesn't arise so that's maybe a better approach.

**Comment by elfring** [comment]
The older library versions have got similar build parameters and [related consequences on software limits](http://www.pcre.org/original/doc/html/pcrelimits.html "Limitations of the PCRE library").
Would you ever like to increase the setting for internal linkage size in a convenient way by an OCaml programming interface?

**Comment by mmottl** [comment]
I usually implement things by need these days.  If you need any further PCRE1 functions, feel free to open a pull request.  Concerning PCRE2, it may actually be best to have a separate library, otherwise questions of backward compatibility and portability may cause too much of a mess.

**Comment by elfring** [comment]
I came along the need to process a regular expression with the size of around 67 KiB.
Would you like to support such bigger search patterns also directly by your OCaml programming interface?

**Comment by mmottl** [comment]
I haven't run into any particular limitations yet.  If you need to make changes to support larger patterns, please submit a pull request.

**Comment by elfring** [comment]
Do you understand the consequences and technical constraints around the property “internal linkage size” for the PCRE(2) library?

**Comment by mmottl** [comment]
No, I have never looked into this.

**Comment by elfring** [comment]
I recommend to look at such technical dependencies again.
Do you care for more challenging data processing possibilities here?

**Comment by mmottl** [comment]
I personally have no such needs.  Please feel free to contribute.

**Comment by elfring** [comment]
How do you think about to use regular expression evaluation services over programming interfaces like “[D-Bus](https://github.com/diml/obus "Pure OCaml implementation of the D-Bus protocol")” and “[CORBA](http://www.corba.org/faq.htm "Description for usage of the Common Object Request Broker Architecture")”?

**Comment by mmottl** [comment]
I have not given it any thought.

**Comment by elfring** [comment]
Would you like to make it configurable in this programming approach if you call a locally installed PCRE library directly or use proxy interfaces instead?

**Comment by mmottl** [comment]
I would certainly not suggest putting anything between the bindings and the library.

**Comment by elfring** [comment]
I propose to make it easier to choose between direct and indirect API calls.
Would it be nice to implement a corresponding D-Bus service by any additional development tools according to your preferences?

**Comment by mmottl** [comment]
Why don't you experiment with proposals in your fork of the library?  If you are happy with any extra functionality, you can always submit a pull request.

**Comment by elfring** [comment]
I prefer to clarify some software design possibilities before corresponding concrete programming at the moment.
The binding passes some data to functions. How easy can it become to switch to proxy interfaces there?

**Comment by mmottl** [comment]
I have no plans for making such deep changes for which I don't see any upside and no time to think about it.  If you have an idea for something you need, please go ahead and implement it.  If it is an improvement, I'll surely merge the changes.

**Comment by elfring** [comment]
Does this information contain a contradiction “I don't see any upside and no time to think about it. …, I'll surely merge the changes.”?
Will an other point in time be better to discuss the mentioned design options further?

**Comment by mmottl** [comment]
I personally don't see any need for the proposal and don't have time to think about how to implement something I don't need.  If I turn out to be wrong about its usefulness, I'll merge proposed changes.

**Comment by elfring** [comment]
I am trying to integrate my needs also into your software library somehow. I assume that I should not continue this approach if you would reject such an attempt already at the beginning because of doubts about its usefulness, shouldn't I?

**Comment by mmottl** [comment]
Your focus should be on solving a problem that personally affects you, irrespective of what others may think.  If you actually need the proposed changes, it shouldn't matter much to you whether or not they get merged.  If you find the solution useful, chances are that others will, too.

**Comment by elfring** [comment]
I would appreciate if my ideas could result in a useful effect also for your software library. If you do not want to pick them up at the moment, I can check still a few other design approaches for my data processing needs.

**Comment by mmottl** [comment]
The easiest way to get your ideas into a project is by simply implementing a small prototype of what you want to do.  If people don't like the idea, you'll learn soon enough, and if they like it, they'll help you.  It's not an effective use of time to discuss potentially intrusive changes with unclear advantages.  Just show some code.

**Comment by elfring** [comment]
I have got an other view about the relevance of “a small prototype”. I imagine that advantages can also be shown without talking about concrete code, can't it?
Are any additional communication means useful in the current situation?

**Comment by mmottl** [comment]
Just play around with some code to see whether it feels like the right thing to do.  Doing will give you 10x more information than talking will ever do.

**Comment by elfring** [comment]
I know a few solutions that can be “right” here. It seems that it will need more communication efforts to adjust change resistance.
I prefer often to clarify some software development aspects before just “doing” something.

**Comment by mmottl** [comment]
I'm afraid I'm too busy to discuss such options.  Please go ahead and implement your idea, I do not have time to help you with that.
