### ISSUE TITLE
7.3.2 native code broken

### ISSUE THREAD

**Issue by ygrek** [mmottl/pcre-ocaml#13]
```
let regexp_clean_name = Pcre.regexp ~flags:[`UTF8] "(?:\\p{L}|\\s)+\\p{L}"

let () =
  match Pcre.extract ~rex:regexp_clean_name "Royden Rego \226\134\146" with
  | [| s |] -> Printf.printf "%S\n" s
  | _ -> assert false
```

built against 7.3.0 : 
```
$ ./q2.native 
"Royden Rego"
$ ./q2.byte
"Royden Rego"
```

7.3.2 :
```
$ ./q2_2.native 
"Royden Rego \226"
$ ./q2_2.byte
"Royden Rego"
```

(I was suspecting the hiding of `[@untagged]` attribute by the signature but it actually does seem to perform correctly on the surface, didn't dig further)

**Comment by mmottl** [comment]
Thanks for the report!  This was a bug in the `external` declaration of the internal regexp `compile` function.  A new release has been made and should be through OPAM soon.
