### ISSUE TITLE
Support for DFA matching, restartable partial matches

### ISSUE THREAD

**Issue by cemerick** [mmottl/pcre-ocaml#14]
I see some support for `PARTIAL` matches (soft, I assume, but I haven't yet double-checked the numerical constants against the PCRE source), but no option to use `pcre_dfa_exec()` and `PCRE_DFA_RESTART` to support restartable partial matches.

Assuming I'm not missing anything, is this something you've worked on at all? If not, would you be open to a contribution along these lines?

**Comment by mmottl** [comment]
I haven't worked on DFA functions in PCRE and don't have an imminent need for that myself.  But if you want to contribute this feature, I'll be happy to merge it.

**Comment by cemerick** [comment]
Thanks for merging #15. :smile:

I wonder if you have any thoughts re: making the "unsafe" match function the sole entry point for DFA matching? https://github.com/mmottl/pcre-ocaml/pull/15#issuecomment-460675032

**Comment by cemerick** [comment]
Fair enough! The little benchmark I tried was certainly contrived. Maybe I'll report back as to whether the difference is tangible once I'm running an actual workload through it.

I think things are good to go. I pulled your changes and verified that the result works well with my DFA-using test programs. Sorry I missed the handling of strings and such with the callouts; I'm quite green to OCaml<=>C hygiene (and OCaml in general, really), so didn't pick up on that.

**Comment by mmottl** [comment]
Thanks, I've just made a new release.  Feel free to submit any improvements in the future!

**Comment by cemerick** [comment]
Thanks, I appreciate it! Don't forget to publish to opam 😊

**Comment by cemerick** [comment]
Excuse me, I didn't realize opam publishing was via PR, and was already in progress. Never mind! 👍

**Comment by mmottl** [comment]
No problem, `dune-release` is your friend :wink:
