### ISSUE TITLE
Unable to install pcre

### ISSUE THREAD

**Issue by abhi18av** [mmottl/pcre-ocaml#16]
Hi @mmottl 

For some reason I'm unable to install a library which depends on this package.

However, I've made sure that that the `libpcre3-dev` library is setup via `apt`

```

root@kali:~# apt install libpcre3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpcre3-dev is already the newest version (2:8.39-11).
0 upgraded, 0 newly installed, 0 to remove and 537 not upgraded.

```

```


root@kali:~# opam install shcaml
[WARNING] Running as root is not recommended
The following actions will be performed:
  ∗ install conf-libpcre 1     [required by pcre]
  ∗ install pcre         7.4.1 [required by shcaml]
  ∗ install shcaml       0.2.1
===== ∗ 3 =====
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[pcre.7.4.1] found in cache
[shcaml.0.2.1] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of conf-libpcre failed at
        "/root/.nix-profile/bin/pkg-config libpcre".

#=== ERROR while compiling conf-libpcre.1 =====================================#
# context     2.0.2 | linux/x86_64 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org#aed13a6d
# path        ~/.opam/default/.opam-switch/build/conf-libpcre.1
# command     ~/.nix-profile/bin/pkg-config libpcre
# exit-code   1
# env-file    ~/.opam/log/conf-libpcre-1627-6d07ae.env
# output-file ~/.opam/log/conf-libpcre-1627-6d07ae.out



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build conf-libpcre 1
└─ 
╶─ No changes have been performed


```

**Comment by mmottl** [comment]
@abhi18av You may want to call `pkg-config` manually to determine whether `libpcre` can be found.  Maybe `libpcre` is not the right name to pass on your platform.  Please feel free to submit a pull request with any changes required to make it work there.

**Comment by abhi18av** [comment]
Hmm, I will have a closer look for sure.

However, I don't think this should happen as I'm using `Kali linux` which is based on `debian` - same as `Ubuntu` and it installs perfectly fine on `Ubuntu` machines.

**Comment by mmottl** [comment]
It clearly seems to be `pkg-config` that is failing here.  Not sure why this happens on your particular distribution.

**Comment by abhi18av** [comment]
Hmm, this got me thinking. Since `kali` uses a custom build from the `ubuntu` base and I was expecting `nix` to behave the same way - it wasn't.

When I installed `pkg-config` from normal `apt` channel it worked fine :)

Thanks @mmottl 👍
