### ISSUE TITLE
Is it possible to build a static version ?

### ISSUE THREAD

**Issue by vsiles** [mmottl/pcre-ocaml#17]
Because of system restriction (can't update a buggy libpcre), I'd like to create an executable statically linked with pcre-ocaml/locally built libpcre. Do you know if that's possible or how to do it ?

**Comment by mmottl** [comment]
It's certainly possible to statically link `libpcre` with the bindings, but I have never tried that with the `dune` build system.  Please let people know here what you had to do to make it work for you, and feel free to submit any patches that make it easy.

**Comment by vsiles** [comment]
Will do if I succeed. So far I'm 8n a world of pain 🤣

**Comment by vsiles** [comment]
I managed to hack something like
```
diff --git a/src/dune b/src/dune
index a0bd636..b51208f 100644
--- a/src/dune
+++ b/src/dune
@@ -6,7 +6,7 @@
     ; NOTE: for debugging before releases
     ; -Wall -pedantic -Wextra -Wunused -Wno-long-long -Wno-keyword-macro
   ))
-  (c_library_flags (:include c_library_flags.sexp))
+  (library_flags ("/home/vsiles/local-pcre/pcre/lib/libpcre.a"))
 )

 (rule
```
but that's not really satisfactory. I need to find a nice way to thread the location of libcpre.a from my build system to dune

**Comment by mmottl** [comment]
The Dune developers might be able to help if you ask for hints in the OCaml forum: https://discuss.ocaml.org

**Comment by mmottl** [comment]
I guess this issue can be closed, since it's more related to Dune features.
