### ISSUE TITLE
"Character value in \x{} or \o{} is too large [9]" for regex with unicode flag

### ISSUE THREAD

**Issue by kavoor** [mmottl/pcre-ocaml#19]
Regex ```\x{10FFFF}/u``` returns the error ```"character value in \x{} or \o{} is too large"```. Per regex101, it appears that this regex should be valid: https://regex101.com/r/whPzHV/1/. Am I missing something?

**Comment by mmottl** [comment]
I don't think you can just add `/u` to interpret this regular expression in Unicode, which is probably how you would indicate this in Perl or PHP.  Instead of e.g.:

```ocaml
let rex = Pcre.regexp "\\x{10FFFF}/u" in
```

You probably want:

```ocaml
let rex = Pcre.regexp ~flags:[`UTF8] "\\x{10FFFF}" in
```
