### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by yallop** [mmottl/pcre-ocaml#23]
With OCaml 4.12.0 and PCRE 7.4.6 the following program produces a segmentation fault:

```ocaml
Pcre.(pmatch ~rex:(regexp "(?:a)*")) (String.make 102400 'a')
```

**Comment by mmottl** [comment]
This seems to be a bug in or limitation of PCRE.  It should presumably return an error when dealing with requests it can't handle.  In this case it seems that the regular expression with this use case may be a little extreme.  In your example we would be matching 102,400 non-capturing subgroups.  PCRE apparently tops out at less than 16,000.

I'm not sure what the application case is, but maybe using a different regular expression would work for you?  Maybe something as simple as `(?:a*)`?  Or processing the input in smaller chunks?

**Comment by yallop** [comment]
> This seems to be a bug in or limitation of PCRE.

I see.  Yes, it's easy to reproduce the problem with the Python bindings:

```
>>> pcre.match('(?:a)*', 'a' * 102400)
Segmentation fault
```

> I'm not sure what the application case is, but maybe using a different regular expression would work for you?

The problem is only in test (benchmarking) code, which can easily be changed.

**Comment by mmottl** [comment]
Thanks, I’ll close this issue.
