### ISSUE TITLE
Function for printing Pcre exceptions?

### ISSUE THREAD

**Issue by mjambon** [mmottl/pcre-ocaml#24]
I didn't find a function that takes a `Pcre.Error` exception and prints a human-friendly representation. By default, we're getting `Pcre.Error(5)` instead of `Pcre.Error(RecursionLimit)`. The plan would be that the user would call `Printexc.register_printer Pcre.string_of_exn`, or maybe just `Pcre.register_exception_printer ()`.

I'll make a PR if you think that's a good idea.

**Comment by mmottl** [comment]
Thanks for the contribution, @mjambon, and sorry for the long delay. I will make a new release soon.
