### ISSUE TITLE
Too conservative GC setting causes exceedingly frequent major heap GC runs

### ISSUE THREAD

**Issue by mfp** [mmottl/pcre-ocaml#3]
I found that what amounted to a bunch of `Pcre.qreplace ~pat ...` calls triggered way too much GC work (mark & sweep of the major heap), and traced it back to  https://github.com/mmottl/pcre-ocaml/blob/master/lib/pcre_stubs.c#L273

In this particular case I can compile the regexps once and reuse them, but forcing a full major heap scan every 500 regexp compilations is clearly several orders of magnitude off, considering it is not unusual to have heaps in the hundreds of MBs...  

I think that `used = 0, max = 1` (i.e., no extra GC pressure)  would be better suited to nowadays' hardware. If regexps take on average ~100 bytes, they're not far away from the 6*8=48 bytes the corresponding custom block takes in OCaml's heap (on 64-bit platforms), so the GC speed computed automatically is going to be about right. Pathological cases can be addressed by the user with manual `Gc.full_major` calls. Any hardcoded maximum number of unreclaimed regexps can be problematic for current users with large heaps, and will likely become comically outdated in the future as memory abundance and usage grows...

**Comment by mmottl** [comment]
I agree, these settings are way too aggressive given pretty much any platform today.  I have updated the distribution but have set the parameters to `used = 1, max = 1000000`.  So you should see only one full GC cycle every million regexp (and chartable) allocations.  This is a lot.  If you generate millions of regular expressions within a short period of time and let them get reclaimed, your program probably doesn't approach the problem efficiently.  Either you may want to cache precompiled regular expressions for reuse then, or use more suitable string matching algorithms.

**Comment by mfp** [comment]
On Fri, Aug 21, 2015 at 06:47:29AM -0700, Markus Mottl wrote:
> I agree, these settings are way too aggressive given pretty much any platform today.  I have updated the distribution but have set the parameters to `used = 1, max = 1000000`.  So you should see only one full GC cycle every million regexp (and chartable) allocations.  This is a lot.  If you generate millions of regular expressions within a short period of time and let them get reclaimed, your program probably doesn't approach the problem efficiently.  Either you may want to cache precompiled regular expressions for reuse then, or use more suitable string matching algorithms.

You're entirely right in that generating millions of regexps in a short time
lapse is certainly wrong.

It is not likely to matter, but I'm not sure there's a real need to speed up
the GC (as said before, I believe it should be able to adjust its own speed
automatically since the external resources take about as much memory as those
in the OCaml heap).

Anyway, for any practical purposes 1 million regexps per major GC cycle should
be enough for anyone ;-)

Thank you,
-- 
Mauricio Fernández

**Comment by mmottl** [comment]
Indeed, there is almost surely no sane application that will ever have a problem with the new setting.  Actual memory usage should remain low for typical applications anyway, because the incremental GC will eventually finish reclaiming all regexp garbage way before a full GC is triggered.  It doesn't harm to be on the safe side triggering an extra full cycle once in a blue moon for long-running applications that allocate and quickly forget many unusually large regexps and don't allocate much else.
