### ISSUE TITLE
full_split seems not to clear previous Group matches

### ISSUE THREAD

**Issue by chenglou** [mmottl/pcre-ocaml#5]
Repro:

```ocaml
(* Convenience helper for printing *)
let printFullSplitResult = List.iteri (fun i x ->
  print_int i;
  print_endline "";
  Pcre.(
    match x with
    | Delim a -> print_endline @@ "Delim " ^ a
    | Group (_, a) -> print_endline @@ "Group " ^ a
    | Text a -> print_endline @@ "Text " ^ a
    | NoGroup -> print_endline @@ "NoGroup"
  )
)

let testR = Pcre.regexp
  ~flags:[Pcre.(`MULTILINE)]
  {|^a(?: (\d))?$|}

let str = {|a 5
bla
a
bla|}
let () = let test = Pcre.full_split ~rex:testR str in
  printFullSplitResult test
```

Actual:
```ocaml
0
Delim a 5
1
Group 5
2
Text
bla

3
Delim a
4
Group
5
Text
bla
```

Expected: that group 4 be `NoGroup` instead of `Group` containing the empty string "".

The regex captures "a" plus a number, if any. If you flip `str` into:
```ocaml
let str = {|a
bla
a 5
bla|}
```

You correctly get:
```
0
Delim a
1
NoGroup
2
Text
bla

3
Delim a 5
4
Group 5
5
Text
bla
```

**Comment by mmottl** [comment]
Thanks for the bug report!  It seems that the underlying PCRE library sets the indices of uncaptured subgroups to only internally useful values while executing a match, but doesn't clear them out before returning.  It hence assumes that the user will only look at subgroups up to the highest matched subgroup.  I've uploaded a new release to OPAM that should fix this issue by explicitly clearing out uncaptured subgroups.
