### ISSUE TITLE
exec_all ~callout regression in 7.2.0

### ISSUE THREAD

**Issue by cyberhuman** [mmottl/pcre-ocaml#6]
Reproducers:

```Pcre.exec_all ~pat:"(?C0)" ~callout:ignore ".";;```
results in `Exception: Invalid_argument "Pcre.pcre_exec_stub: illegal position".`

```Pcre.exec_all ~pat:"." ~callout:ignore ".";;```
results in an infinite loop.

**Comment by mmottl** [comment]
@cyberhuman Thanks for the bug report!  A fixed release is on its way through OPAM.  Callouts should now work again.
