### ISSUE TITLE
Improve error reporting for failed parsing of regular expressions

### ISSUE THREAD

**Issue by elfring** [mmottl/pcre-ocaml#7]
[The function “register_printer” is used](https://github.com/mmottl/pcre-ocaml/blob/258b72cf6ec67362a137ebc434a5a52fd2610077/setup.ml#L414 "Better error reporting?") to inform about a few exceptional data processing situations. [I stumbled on a questionable error message](https://github.com/coccinelle/coccinelle/issues/89#issue-187709958 "Fix data processing for advanced regular expressions in SmPL constraints") during an attempt to work with a big alternation in a generated regular expression.

Would you like to extend your error handling approaches for better explanation of parsing failures there?

**Comment by mmottl** [comment]
The error tags that are passed with the raised `Error` exception correspond to the error codes returned by the underlying C-library.  I am not sure to which extent one can extract more detailed information from it.  If you merely want to register default printers with the standard `Printexc`-module to better identify the errors, I'll be happy to merge a corresponding pull request.

**Comment by elfring** [comment]
I would appreciate to see a better explanation than the message “`exception Pcre.Error(_)`”.
Do you know any more detailed error information already when a passed regular expression would contain a syntax error (because of a typo) for example?

**Comment by elfring** [comment]
:confused: Do I understand the current source files of this software library in the way correctly that the PCRE exceptions were not transformed into useful error messages so far?

:crystal_ball: Will an approach like the following work a bit better then at the end of [the file “pcre.ml”](https://github.com/mmottl/pcre-ocaml/blob/725120d182d39e4e9e8e21e74e2cbae8ca293db7/lib/pcre.ml "Update candidate")?

```OCaml
let () = Printexc.register_printer
         (function
         | Error ex
           -> (match ex with
              | BadPartial
                -> Some (Printf.sprintf "Pattern contains items that cannot be used together with partial matching.")
              | BadPattern (msg, pos)
                -> Some (Printf.sprintf "Error in pattern at %d: %s" pos msg)
              | BadUTF8
                -> Some (Printf.sprintf "UTF8 string being matched is invalid.")
              | BadUTF8Offset
                -> Some (Printf.sprintf "UTF8 string being matched with offset is invalid.")
              | InternalError msg
                -> Some (Printf.sprintf "Unknown behaviour: %s" msg)
              | MatchLimit
                -> Some (Printf.sprintf "Maximum allowed number of match attempts with backtracking or recursion is reached during matching.")
              | Partial
                -> Some (Printf.sprintf "String matched the pattern only partially.")
              | RecursionLimit
                -> Some (Printf.sprintf "Recursion limit")
              )
         | _ -> None
         )
```

:sunny:

**Comment by mmottl** [comment]
Correct, PCRE only gives you certain error codes that are translated directly to OCaml tags.  It's left to the user to translate them to something more insightful.  This may depend on the application, which is why there is no standard exception printer.

If you want a better standard printer, I wouldn't use long string messages, I would simply convert the tags verbatim so that the error looks exactly as if you wrote the exception in OCaml code, e.g.:

```ocaml
Pcre.Error (BadPattern ("whatever", 42))
```

This is generally good enough for users and more precise for developers.  For that purpose you may want to implement a separate `error_to_string` function.

**Comment by elfring** [comment]
>For that purpose you may want to implement a separate `error_to_string` function.

* Do you prefer to call such a function at an other source code position?
* How would a display from your suggestion look different from my addition above?
* Are detailed error messages more useful?

**Comment by mmottl** [comment]
- No, but the code would look cleaner with an `error_to_string` function.
- The error would be displayed exactly as written above (`Pcre.Error ...`).
- Error messages should contain all the details necessary to understand the error.  Displaying string representations of exceptions is as unambiguous and detailed as it can get.  More prosaic messages may be better for end users, but developers usually prefer the former.

**Comment by elfring** [comment]
* Are you going to add the function “`error_to_string`”?
* Would any further translations be needed?

**Comment by mmottl** [comment]
No, I don't have any personal need for that right now.  Please submit pull requests to contribute features you need.
