### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [mmottl/pcre-ocaml#9]
Would you like to add more error handling for return values from functions like the following?
- `caml_alloc_final` ⇒ [`pcre_compile_stub`](https://github.com/mmottl/pcre-ocaml/blob/ac3c1ea3da0d37fba571dc229cd77184a4eef8d1/lib/pcre_stubs.c#L252 "PCRE pattern compilation")
- [`pcre_malloc`](http://www.pcre.org/original/doc/html/pcreapi.html#SEC4 "Memory allocation") ⇒ [`pcre_set_imp_match_limit_stub`](https://github.com/mmottl/pcre-ocaml/blob/ac3c1ea3da0d37fba571dc229cd77184a4eef8d1/lib/pcre_stubs.c#L339 "Sets a match limit for a regular expression")

**Comment by mmottl** [comment]
`caml_alloc_final` should raise an exception if the runtime were unable to allocate memory.  Many programs don't check for `NULL` values returned by `malloc`, because it may be hard if not impossible to recover after that anyway so there shouldn't be any need to change anything.

**Comment by elfring** [comment]
>`caml_alloc_final` should raise an exception if the runtime were unable to allocate memory.

How should this happen when it is supposed that the function will return “a value”?


>Many programs don't check for `NULL` values returned by `malloc`, because it may be hard if not impossible to recover after that anyway so there shouldn't be any need to change anything.

I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by mmottl** [comment]
The OCaml runtime uses `longjmp` to raise exceptions, i.e. `caml_alloc_final` would never return, it would jump straight to the innermost exception handler on the call stack.

Feel free to harden the `pcre_malloc` calls by checking for `NULL` values.  In practice it wouldn't make that much of a difference, because the OCaml runtime will likely not allow your program to respond in any meaningful way if you are out of memory, and you'll typically know anyway that your program ran out of memory.

Note, btw., that you should be replacing `malloc` with `caml_stat_alloc` in OCaml bindings: it will raise an OOM exception for you.

**Comment by elfring** [comment]
* Do you eventually prefer [the development methodology “Crash-only software”](https://en.wikipedia.org/wiki/Crash-only_software "Crashing software intentionally?")?
* Would you generally like to use the function “`caml_stat_alloc`” instead of “`malloc`” in OCaml bindings?

**Comment by mmottl** [comment]
It is very hard to recover from OOM errors, especially if your language doesn't use manual memory management.  The only upside I see would be that the user knows for sure that OOM caused a crash, but typically they would know that anyway.  Again, feel free to submit a pull request if the improvement matters to you.

It's generally a good idea to use `caml_stat_alloc` in OCaml bindings, but you have to make sure that the running code is holding the OCaml runtime lock at that point.

**Comment by elfring** [comment]
How do you think about the possibility that the function “`caml_stat_alloc`” could directly be called by the PCRE C library?

**Comment by mmottl** [comment]
There must be a reason why PCRE provided its own allocation function.  Even if it just referred to `malloc` right now, I wouldn't risk calling it directly (or `caml_stat_alloc`).  Maybe the PCRE authors had future changes in mind that could improve performance or collect useful statistics internally.

**Comment by elfring** [comment]
I find this view partly inappropriate. There are more reasons to select an other memory allocator occasionally.
